name: career-connect-frontend
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 5173:5173
    env_file:
      - .env
    volumes:
      - ./src:/code/src
