import { UserType } from '../schemas/userSchema';

export const users: UserType[] = [
  {
    firstName: 'Than Win',
    lastName: 'Hline',
    email: 'admin@example.com',
    password: '88888888',
    location: { country: 'Bangladesh', city: 'Dhaka' },
    accessStatus: true,
    twoStepAuthentication: false,
    phoneNumber: '008801871675808',
    isEmailVerified: true,
    role: 'admin',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: 'Alice',
    lastName: 'Johnson',
    email: 'alice@example.com',
    password: '88888888',
    location: { country: 'USA', city: 'New York' },
    accessStatus: true,
    twoStepAuthentication: false,
    phoneNumber: '1234567890',
    isEmailVerified: true,
    role: 'user',
    createdAt: new Date(),
    updatedAt: new Date(),
    worksAt: '67e87694b3424acf88b26339',
  },
  {
    firstName: 'Bob',
    lastName: 'Smith',
    email: 'bob@example.com',
    password: '88888888',
    location: { country: 'UK', city: 'London' },
    accessStatus: false,
    twoStepAuthentication: true,
    phoneNumber: '447911123456',
    isEmailVerified: false,
    role: 'recruiter',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: 'Carlos',
    lastName: 'Martinez',
    email: 'carlos@example.com',
    password: '88888888',
    location: { country: 'Spain', city: 'Madrid' },
    accessStatus: true,
    twoStepAuthentication: false,
    phoneNumber: '34911123456',
    isEmailVerified: true,
    role: 'user',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: 'Diana',
    lastName: 'Lee',
    email: 'diana@example.com',
    password: '88888888',
    location: { country: 'Canada', city: 'Toronto' },
    accessStatus: true,
    twoStepAuthentication: false,
    phoneNumber: '16475551234',
    isEmailVerified: false,
    role: 'recruiter',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: 'Emily',
    lastName: 'Wang',
    email: 'emily@example.com',
    password: '88888888',
    location: { country: 'Australia', city: 'Sydney' },
    accessStatus: true,
    twoStepAuthentication: true,
    phoneNumber: '61412345678',
    isEmailVerified: true,
    role: 'user',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: 'Frank',
    lastName: 'Zhang',
    email: 'frank@example.com',
    password: '88888888',
    location: { country: 'China', city: 'Shanghai' },
    accessStatus: true,
    twoStepAuthentication: false,
    phoneNumber: '8613812345678',
    isEmailVerified: true,
    role: 'recruiter',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: 'Grace',
    lastName: 'Kim',
    email: 'grace@example.com',
    password: '88888888',
    location: { country: 'South Korea', city: 'Seoul' },
    accessStatus: true,
    twoStepAuthentication: false,
    phoneNumber: '821012345678',
    isEmailVerified: false,
    role: 'user',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: 'Hassan',
    lastName: 'Ali',
    email: 'hassan@example.com',
    password: '88888888',
    location: { country: 'UAE', city: 'Dubai' },
    accessStatus: false,
    twoStepAuthentication: true,
    phoneNumber: '971501234567',
    isEmailVerified: true,
    role: 'recruiter',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: 'Isabelle',
    lastName: 'Dubois',
    email: 'isabelle@example.com',
    password: '88888888',
    location: { country: 'France', city: 'Paris' },
    accessStatus: true,
    twoStepAuthentication: false,
    phoneNumber: '33612345678',
    isEmailVerified: true,
    role: 'user',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: 'Jamal',
    lastName: 'Khan',
    email: 'jamal@example.com',
    password: '88888888',
    location: { country: 'Pakistan', city: 'Lahore' },
    accessStatus: true,
    twoStepAuthentication: false,
    phoneNumber: '923001234567',
    isEmailVerified: false,
    role: 'recruiter',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: 'Umar',
    lastName: 'Ali',
    email: 'umar@example.com',
    password: '88888888',
    location: { country: 'Pakistan', city: 'Karachi' },
    accessStatus: true,
    twoStepAuthentication: false,
    phoneNumber: '923001234567',
    isEmailVerified: true,
    role: 'user',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: 'Vanessa',
    lastName: 'Wright',
    email: 'vanessa@example.com',
    password: '88888888',
    location: { country: 'UK', city: 'London' },
    accessStatus: false,
    twoStepAuthentication: true,
    phoneNumber: '447911123456',
    isEmailVerified: true,
    role: 'recruiter',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: 'William',
    lastName: 'Zhao',
    email: 'william@example.com',
    password: '88888888',
    location: { country: 'China', city: 'Shanghai' },
    accessStatus: true,
    twoStepAuthentication: false,
    phoneNumber: '8613012345678',
    isEmailVerified: true,
    role: 'user',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: 'Ximena',
    lastName: 'Lopez',
    email: 'ximena@example.com',
    password: '88888888',
    location: { country: 'Colombia', city: 'Bogotá' },
    accessStatus: false,
    twoStepAuthentication: true,
    phoneNumber: '573001234567',
    isEmailVerified: false,
    role: 'recruiter',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: 'Yusuf',
    lastName: 'Khan',
    email: 'yusuf@example.com',
    password: '88888888',
    location: { country: 'UAE', city: 'Dubai' },
    accessStatus: true,
    twoStepAuthentication: false,
    phoneNumber: '971501234567',
    isEmailVerified: true,
    role: 'user',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: 'Zara',
    lastName: 'Ahmed',
    email: 'zara@example.com',
    password: '88888888',
    location: { country: 'India', city: 'Hyderabad' },
    accessStatus: true,
    twoStepAuthentication: true,
    phoneNumber: '918801234567',
    isEmailVerified: true,
    role: 'recruiter',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: 'Adam',
    lastName: 'Smith',
    email: 'adam@example.com',
    password: '88888888',
    location: { country: 'USA', city: 'New York' },
    accessStatus: false,
    twoStepAuthentication: false,
    phoneNumber: '12125550123',
    isEmailVerified: true,
    role: 'user',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: 'Bianca',
    lastName: 'Santos',
    email: 'bianca@example.com',
    password: '88888888',
    location: { country: 'Brazil', city: 'São Paulo' },
    accessStatus: true,
    twoStepAuthentication: true,
    phoneNumber: '5511999999999',
    isEmailVerified: false,
    role: 'recruiter',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: 'Carlos',
    lastName: 'Fernandez',
    email: 'carlos@example.com',
    password: '88888888',
    location: { country: 'Spain', city: 'Barcelona' },
    accessStatus: true,
    twoStepAuthentication: false,
    phoneNumber: '34600123456',
    isEmailVerified: true,
    role: 'user',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: 'Dina',
    lastName: 'Nasr',
    email: 'dina@example.com',
    password: '88888888',
    location: { country: 'Egypt', city: 'Alexandria' },
    accessStatus: false,
    twoStepAuthentication: true,
    phoneNumber: '201155512345',
    isEmailVerified: false,
    role: 'recruiter',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
