name: career-connect-backend

services:
  mongo-server:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - career-network
  api:
    build: .
    restart: unless-stopped
    env_file: .env
    ports:
      - 5100:5100
    depends_on:
      - mongo-server
    volumes:
      - .:/usr/src/app
      - /app/node_modules
    networks:
      - career-network

volumes:
  mongo-data:

networks:
  career-network:
    driver: bridge
