name: career-connect-backend

services:
  mongo-server:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - career-network
  redis-server:
    image: redis/redis-stack
    restart: unless-stopped
    ports:
      - 6379:6379
      - 8001:8001
    env_file: .env
    networks:
      - career-network

  api:
    build: .
    restart: unless-stopped
    env_file: .env
    ports:
      - 5100:5100
    depends_on:
      - mongo-server

    networks:
      - career-network
    volumes:
      - ./src:/code/src

volumes:
  mongo-data:

networks:
  career-network:
    driver: bridge
